const Widget = {
	Empty: 'Empty',
	RaisedButton: 'RaisedButton',
	FlatButton: 'FlatButton',
	OutlineButton: 'OutlineButton',
	IconButton: 'IconButton',
	FloatingActionButton: 'FloatingActionButton',
	Text: 'Text',
	Image: 'Image',
	Card: 'Card',
	RichText: 'RichText',
	Icon: 'Icon',
	ListTile: 'ListTile',
	Chip: 'Chip',
	Divider: 'Divider',
	Container: 'Container',
	Paper: 'Paper',
	Row: 'Row',
	Column: 'Column',
	ListView: 'ListView',
	GridView: 'GridView',
	Wrap: 'Wrap',
	TextField: 'TextField',
	Slider: 'Slider',
	DropdownButton: 'DropdownButton',
	Radio: 'Radio',
	Checkbox: 'Checkbox',
	Switch: 'Switch',
	Form: 'Form',
	CheckboxListTile: 'CheckboxListTile',
	RadioListTile: 'RadioListTile',
	SwitchListTitle: 'SwitchListTitle',
	ExpansionTile: 'ExpansionTile',
	TabBar: 'TabBar',
	BottomNavigationBar: 'BottomNavigationBar',
	Stepper: 'Stepper',
	PageView: 'PageView',
	ExpansionPanel: 'ExpansionPanel',
	IndexedStack: 'IndexedStack',
	Carousel: 'Carousel',
	Map: 'Map',
	Webview: 'Webview',
	Swipe_Cards: 'Swipe_Cards',
	SMS_Code_Confirm: 'SMS_Code_Confirm',
	Country_Picker: 'Country_Picker',
	AutoComplete: 'AutoComplete',
	Rating: 'Rating',
}

const ContainerType = {
  Page: {
  	Normal: 'Normal',
  	Login: 'Login',
  	SignUp: 'SignUp',
  	OnBoard: 'OnBoard',
  	Chat: 'Chat'
  },
  Popup: {
    Dialog: 'Dialog',
    Drawer:  'Drawer',
    BottomSheet: 'BottomSheet',
    // Snackbar: 5,
    Tooltip: 'Tooltip',
    DatePicker: 'DatePicker',
  },
  container: {
    TabView: 'TabView',
    PageView: 'PageView',
    IndexedStack: 'IndexedStack',
    Stepper: 'Stepper',
    ExpansionPanel: 'ExpansionPanel',
    Form: 'Form'
  }
}

export { Widget, ContainerType };
