export default ["Cambium Learning Group, Inc.",
"Genpact Limited",
"Twitter, Inc.",
"iShares MSCI Emerging Markets Asia Index Fund",
"Microvision, Inc.",
"HCP, Inc.",
"Liberty Tax, Inc.",
"Cogent Communications Holdings, Inc.",
"Advantage Oil & Gas Ltd",
"Brookdale Senior Living Inc.",
"Blackrock MuniHoldings Quality Fund, Inc.",
"Tsakos Energy Navigation Ltd",
"Yirendai Ltd.",
"Yamana Gold Inc.",
"Carbonite, Inc.",
"Westport Fuel Systems Inc",
"CVR Partners, LP",
"Avadel Pharmaceuticals plc",
"Neovasc Inc.",
"Forrester Research, Inc.",
"Endurance International Group Holdings, Inc.",
"Infosys Limited",
"Hunter Maritime Acquisition Corp.",
"United Community Bancorp",
"Acacia Research Corporation",
"FIRST REPUBLIC BANK",
"Determine, Inc. ",
"ACNB Corporation",
"Popular, Inc.",
"Destination XL Group, Inc.",
"CoreCivic, Inc.",
"Omeros Corporation",
"First Trust Intermediate Duration Preferred & Income Fund",
"LM Funding America, Inc.",
"Blackrock Municipal 2018 Term Trust",
"KKR & Co. L.P.",
"First Trust Indxx Global Natural Resources Income ETF",
"Fulton Financial Corporation",
"Alexander & Baldwin Holdings, Inc.",
"Vitamin Shoppe, Inc",
"Ooma, Inc.",
"Hess Corporation",
"Condor Hospitality Trust, Inc.",
"Wells Fargo & Company",
"Lianluo Smart Limited",
"SLM Corporation",
"500.com Limited",
"SilverBow Resorces, Inc.",
"Public Storage",
"Richmont Mines, Inc."]