export default ["Dried Apple",
"Chicken - Bones",
"Chocolate - Milk, Callets",
"Chocolate - Milk, Callets",
"Veal - Insides, Grains",
"Oil - Macadamia",
"Cheese - Grie Des Champ",
"Worcestershire Sauce",
"Beef Dry Aged Tenderloin Aaa",
"Longos - Chicken Curried",
"Wine - Black Tower Qr",
"Pork - Bacon, Double Smoked",
"Wine - White, Schroder And Schyl",
"Nut - Walnut, Pieces",
"Oregano - Fresh",
"Vodka - Smirnoff",
"Lidsoupcont Rp12dn",
"Sauce - Rosee",
"Chocolate - Semi Sweet",
"Island Oasis - Mango Daiquiri",
"Longos - Penne With Pesto",
"Turkey - Breast, Double",
"Cheese - Parmigiano Reggiano",
"Plastic Arrow Stir Stick",
"Wine - Mas Chicet Rose, Vintage",
"Longos - Penne With Pesto",
"Bowl 12 Oz - Showcase 92012",
"Wine - Red, Marechal Foch",
"Sauce Bbq Smokey",
"Wine - Pinot Noir Latour",
"Extract - Raspberry",
"Bag Clear 10 Lb",
"Cheese - Parmesan Cubes",
"Wine - Red, Marechal Foch",
"Juice - Propel Sport",
"Cookie Dough - Peanut Butter",
"Syrup - Monin - Passion Fruit",
"Appetizer - Lobster Phyllo Roll",
"Juice - Ocean Spray Cranberry",
"Blueberries",
"Tomato - Plum With Basil",
"Mushroom - Chantrelle, Fresh",
"Liqueur Banana, Ramazzotti",
"Cheese - Sheep Milk",
"Longos - Chicken Wings",
"Clams - Littleneck, Whole",
"Croissants Thaw And Serve",
"Bowl 12 Oz - Showcase 92012",
"Lid Tray - 16in Dome",
"Creamers - 10%"]